spring:
  datasource:
    url: jdbc:postgresql://postgres_db:5432/compose-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    platform: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
