auth0:
  audience: 1E4bHwGjDsGhgkLHcrlk0xemreuSXpnd

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/snippet_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    platform: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://dev-c4l43o2ndcdikqar.us.auth0.com/

logging:
  level:
    org:
      springframework:
        security: DEBUG