auth0:
  audience: 1E4bHwGjDsGhgkLHcrlk0xemreuSXpnd

redis:
  host: localhost
  port: 6379

stream:
  key: "mystream"

groups:
  product: "productcreated"


spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://dev-c4l43o2ndcdikqar.us.auth0.com/

logging:
  level:
    org:
      springframework:
        security: DEBUG
